### ISSUE TITLE
Working directory concept unclear

### ISSUE THREAD

**Issue by ArneBachmann** [rcenvironment/rce#18]
Under which circumstances will the "Working directory" be selected?

No matter what I choose on the wizard pages before, it´s always "Tool Directory".
Could it be, that the "Tool directory" actually refers to the temporary working directory that RCE automatically creates unless the option "do not copy" is enabled?

This is all very confusing and uses bad terminology.
![rce2](https://user-images.githubusercontent.com/20544098/36665279-006d2c0a-1adf-11e8-8826-b1502662509c.png)

**Comment by rmischke-dlr** [comment]
Personally, I fully agree that the current terminology is confusing. It developed like this for historical reasons, and we would most likely design it differently now. But at the same time, we are hesitant to change it bit by bit, because this may cause even more confusion for existing users. 

Instead, we have a full rework of the tool integration concept underway. This includes a new and more understandable UI (which is already implemented), conceptual changes regarding tool publishing and versioning, and various other changes. Sadly, these changes won't make it into RCE 9.x yet, as there are still some conceptual issues to work out.

I'll add your feedback to the existing issue to make sure the new terminology and UI handles these cases better.

**Comment by rmischke-dlr** [comment]
For reference, [this](https://mantis.sc.dlr.de/view.php?id=12389) is the ongoing issue for reworking the tool integration UI, which also includes some of the conceptual rework.

**Comment by rmischke-dlr** [comment]
I opened [one issue](https://mantis.sc.dlr.de/view.php?id=15985) for the general terminology topic, and [another one](https://mantis.sc.dlr.de/view.php?id=15986) for potential short-term fixes in the existing UI.

**Comment by ArneBachmann** [comment]
OK, I will continue dialog in Mantis, but helpful answers would be appreciated here in the public tracker as well.
