### ISSUE TITLE
Input Provider Path-incl.-Filename-Length Limited to 140 character

### ISSUE THREAD

**Issue by elPlaneador** [rcenvironment/rce#29]
Complete path length incl filename is limited. 142/141 character are marked red. 

Limit seems to be independent from OperatingSystem (Win + Linux). 

![grafik](https://user-images.githubusercontent.com/47039730/114990607-f8b8a480-9e98-11eb-94f5-3bdb31f2208a.png)

**Comment by aweinert** [comment]
Hi, thanks for reporting this. Red fields on the placeholder page of the workflow execution wizard generally point to some sort of placeholder validation issue. However, such validation issues should not prevent you from executing the workflow. When clicking "Ok" in that dialog, you should be presented with a list of validation errors, in this case containing the (slightly misleading) message "Missing value for placeholder." You should be able to safely ignore this message and proceed with executing the workflow.

We have implemented a validation that checks for path lengths >140 characters since Windows in some corner cases still has issues with such paths. Moreover, we cannot simply disable this validation when using RCE on a Linux machine, since the input provider may be executed remotely, e.g., on a Windows machine. This check for the platform on which the Input Provider is executed is only carried out at execution time and can thus not influence messages at validation time.

Feel free to close this issue if your question has been answered, otherwise we will close in about a week if we do not hear back from you.
