### ISSUE TITLE
Cannot clone repository

### ISSUE THREAD

**Issue by ArneBachmannDLR** [rcenvironment/rce#31]
Seems like there is a limit to cloning LFS items:

```
D:\forks\_old dlr>git clone https://github.com/rcenvironment/rce.git
Cloning into 'rce'...
remote: Enumerating objects: 82881, done.
remote: Counting objects: 100% (16930/16930), done.
remote: Compressing objects: 100% (6359/6359), done.
remote: Total 82881 (delta 7509), reused 13932 (delta 5760), pack-reused 65951
Receiving objects: 100% (82881/82881), 111.61 MiB | 952.00 KiB/s, done.
Resolving deltas: 100% (41213/41213), done.
Updating files: 100% (6175/6175), done.
Downloading de.rcenvironment.binaries.dakota.linux.x86_64/resources/binaries-lfs/dakota (38 MB)
Error downloading object: de.rcenvironment.binaries.dakota.linux.x86_64/resources/binaries-lfs/dakota (1a626f7): Smudge error: Error downloading de.rcenvironment.binaries.dakota.linux.x86_64/resources/binaries-lfs/dakota (1a626f77d05837d3de2cb8a12757d91b835e2d5f5b214539f3550d006921978d): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to D:\forks\_old dlr\rce\.git\lfs\logs\20210420T092503.230755.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: de.rcenvironment.binaries.dakota.linux.x86_64/resources/binaries-lfs/dakota: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by ArneBachmannDLR** [comment]
After `set GIT_LFS_SKIP_SMUDGE=true` running `git restore --source=HEAD :/` worked, no idea what that means though.

**Comment by aweinert** [comment]
Hi Arne, thanks for reporting this. Indeed, there is a limit on both free storage and free traffic of 1GB each (1GB per month, respectively) when using LFS, see https://docs.github.com/en/github/managing-large-files/about-storage-and-bandwidth-usage. In RCE we use LFS to store some of our external dependencies in order to keep our build process as independent of external resources as possible.

I see that you were later able to check out the repository, so please let us know if you require any action from us in the short term. For the long term, we will evaluate our build process and will see whether we can resolve this depedency on Github traffic quotas.

Feel free to close this issue if your question has been answered, otherwise we will close in about a week if we do not hear back from you.

**Comment by ArneBachmannDLR** [comment]
Ok, you might want to document the workaround above to the end user (or use this issue as a reminder), but I close this ticket now.
